version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.uat
    image: jackson-app:uat
    container_name: jackson-app-uat
    restart: always
    ports:
      - "5000:5000"
