version: '3.8'

services:
  app:
    build: .
    container_name: jackson-app
    restart: always
    ports:
      - "4001:4001"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: jackson-redis
    restart: always
    ports:
      - "6379:6379"
