server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: jackson-app-backend
          __path__: /var/log/app/combined.log
  - job_name: app_errors
    static_configs:
      - targets:
          - localhost
        labels:
          job: jackson-app-backend
          level: error
          __path__: /var/log/app/error.log
