sonar.projectKey=jackson-app
sonar.projectName=Jackson App
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/uploads/**,**/data/**,**/analysis/**,**/docs/**,**/postman/**,**/requirment_docs/**,**/rewards-admin-frontend/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
