apiVersion: v1
kind: Service
metadata:
  name: jackson-app
  namespace: jackson-app
spec:
  selector:
    app: jackson-app
  ports:
    - name: http
      port: 80
      targetPort: 4001
  type: ClusterIP
